# =============================================================================
# Feed options
# =============================================================================
# Each herd section has:
# - cft_id: cft identifier as integer
# - display_name: cft identifier as text
# - display_name: optional UI label
# =============================================================================

[[feed]]
cft_id = 1
display_name = "Grass fresh managed - on farm"
certified = false
region_name = "Global (world)"
cft_name = "grass_fresh_managed"
fwi_to_dmi = 0.16
production_location = "on-farm"

[[feed]]
cft_id = 8
display_name = "Maize silage"
certified = false
region_name = "Global (world)"
cft_name = "maize_silage"
fwi_to_dmi = 0.283
production_location = "on-farm"

[[feed]]
cft_id = 6
display_name = "Grass silage - on farm"
certified = false
region_name = "Global (world)"
cft_name = "grass_silage"
fwi_to_dmi = 0.37
production_location = "on-farm"

[[feed]]
cft_id = 9
display_name = "Lucerne / Alfalfa silage"
certified = false
region_name = "Global (world)"
cft_name = "lucerne_alfalfa_silage"
fwi_to_dmi = 0.37
production_location = "on-farm"

[[feed]]
cft_id = 4
display_name = "Grass hay - on farm"
certified = false
region_name = "Global (world)"
cft_name = "grass_hay"
fwi_to_dmi = 0.845
production_location = "on-farm"

[[feed]]
cft_id = 11
display_name = "Straw"
certified = false
region_name = "Global (world)"
cft_name = "straw"
fwi_to_dmi = 0.902
production_location = "on-farm"

[[feed]]
cft_id = 13
display_name = "Wheat"
certified = false
region_name = "Poland"
cft_name = "wheat"
fwi_to_dmi = 0.868
production_location = "on-farm"

[[feed]]
cft_id = 20
display_name = "Other cereals"
certified = false
region_name = "European Union + EFTA"
cft_name = "other_cereals"
fwi_to_dmi = 0.877
production_location = "on-farm"

[[feed]]
cft_id = 16
display_name = "Oats"
certified = false
region_name = "Poland"
cft_name = "oats"
fwi_to_dmi = 0.889
production_location = "on-farm"

[[feed]]
cft_id = 18
display_name = "Rye"
certified = false
region_name = "Poland"
cft_name = "rye"
fwi_to_dmi = 0.872
production_location = "on-farm"

[[feed]]
cft_id = 14
display_name = "Barley"
certified = false
region_name = "Poland"
cft_name = "barley"
fwi_to_dmi = 0.869
production_location = "on-farm"

[[feed]]
cft_id = 15
display_name = "Maize / corn grain"
certified = false
region_name = "European Union + EFTA"
cft_name = "maize_grain"
fwi_to_dmi = 0.872
production_location = "on-farm"

[[feed]]
cft_id = 31
display_name = "Rapeseed cake/meal"
certified = false
region_name = "Poland"
cft_name = "rapeseed_meal"
fwi_to_dmi = 0.872
production_location = "off-farm"

[[feed]]
cft_id = 27
display_name = "Compound dairy feed: default (15% soy)"
certified = false
region_name = "Global (world)"
cft_name = "compound_15_soy"
fwi_to_dmi = 0.894
production_location = "off-farm"

[[feed]]
cft_id = 29
display_name = "Compound dairy feed: low (8%) soy, high protein"
certified = false
region_name = "Global (world)"
cft_name = "compound_8_soy"
fwi_to_dmi = 0.896
production_location = "off-farm"

[[feed]]
cft_id = 28
display_name = "Compound dairy feed: high (46%) soy, high protein"
certified = false
region_name = "Global (world)"
cft_name = "compound_46_soy"
fwi_to_dmi = 0.886
production_location = "off-farm"

[[feed]]
cft_id = 30
display_name = "Soybean cake/meal"
certified = false
region_name = "Global (world)"
cft_name = "soybean_meal"
fwi_to_dmi = 0.874
production_location = "off-farm"

[[feed]]
cft_id = 36
display_name = "Soybean"
certified = false
region_name = "Poland"
cft_name = "soybean"
fwi_to_dmi = 0.885
production_location = "off-farm"

[[feed]]
cft_id = 42
display_name = "Fodder beet"
certified = false
region_name = "Poland"
cft_name = "fodder_beet"
fwi_to_dmi = 0.22
production_location = "off-farm"

[[feed]]
cft_id = 48
display_name = "Sugar beet pulp"
certified = false
region_name = "Poland"
cft_name = "sugar_beet_pulp"
fwi_to_dmi = 0.907
production_location = "off-farm"

[[feed]]
cft_id = 78
display_name = "Molasses"
certified = false
region_name = "Poland"
cft_name = "molasses"
fwi_to_dmi = 0.723
production_location = "off-farm"

[[feed]]
cft_id = 23
display_name = "Dried distillers grains (DDGS) / Draff"
certified = false
region_name = "European Union + EFTA"
cft_name = "dried_distillers_grains"
fwi_to_dmi = 0.901
production_location = "off-farm"

[[feed]]
cft_id = 24
display_name = "Brewerâ€™s grain"
certified = false
region_name = "European Union + EFTA"
cft_name = "brewers_grain"
fwi_to_dmi = 0.903
production_location = "off-farm"

[[feed]]
cft_id = 35
display_name = "Other oil cake/meal"
certified = false
region_name = "Global (world)"
cft_name = "other_oil_meal"
fwi_to_dmi = 0.891
production_location = "off-farm"

[[feed]]
cft_id = 80
display_name = "Mineral mix"
certified = false
region_name = "European Union + EFTA"
cft_name = "mineral_mix"
fwi_to_dmi = 0.95
production_location = "off-farm"

[[feed]]
cft_id = 75
display_name = "Bypass fat"
certified = false
region_name = "European Union + EFTA"
cft_name = "bypass_fat"
fwi_to_dmi = 0.994
production_location = "off-farm"