# =============================================================================
# Feed options
# =============================================================================
# Each herd section has:
# - cft_id: cft identifier as integer
# - display_name: cft identifier as text
# - display_name: optional UI label
# =============================================================================

[[feed]]
cft_id = 1
display_name = "Grass fresh managed - on farm"
certified = false
region_name = "Global (world)"
cft_name = "grass_fresh_managed"

[[feed]]
cft_id = 8
display_name = "Maize silage"
certified = false
region_name = "Global (world)"
cft_name = "maize_silage"

[[feed]]
cft_id = 6
display_name = "Grass silage - on farm"
certified = false
region_name = "Global (world)"
cft_name = "grass_silage"

[[feed]]
cft_id = 9
display_name = "Lucerne / Alfalfa silage"
certified = false
region_name = "Global (world)"
cft_name = "lucerne_alfalfa_silage"

[[feed]]
cft_id = 4
display_name = "Grass hay - on farm"
certified = false
region_name = "Global (world)"
cft_name = "grass_hay"

[[feed]]
cft_id = 11
display_name = "Straw"
certified = false
region_name = "Global (world)"
cft_name = "straw"

[[feed]]
cft_id = 13
display_name = "Wheat"
certified = false
region_name = "Poland"
cft_name = "wheat"

[[feed]]
cft_id = 20
display_name = "Other cereals"
certified = false
region_name = "European Union + EFTA"
cft_name = "other_cereals"

[[feed]]
cft_id = 16
display_name = "Oats"
certified = false
region_name = "Poland"
cft_name = "oats"

[[feed]]
cft_id = 18
display_name = "Rye"
certified = false
region_name = "Poland"
cft_name = "rye"

[[feed]]
cft_id = 14
display_name = "Barley"
certified = false
region_name = "Poland"
cft_name = "barley"

[[feed]]
cft_id = 15
display_name = "Maize / corn grain"
certified = false
region_name = "European Union + EFTA"
cft_name = "maize_grain"

[[feed]]
cft_id = 31
display_name = "Rapeseed cake/meal"
certified = false
region_name = "Poland"
cft_name = "rapeseed_meal"

[[feed]]
cft_id = 27
display_name = "Compound dairy feed: default (15% soy)"
certified = false
region_name = "Global (world)"
cft_name = "compound_15_soy"

[[feed]]
cft_id = 29
display_name = "Compound dairy feed: low (8%) soy, high protein"
certified = false
region_name = "Global (world)"
cft_name = "compound_8_soy"

[[feed]]
cft_id = 28
display_name = "Compound dairy feed: high (46%) soy, high protein"
certified = false
region_name = "Global (world)"
cft_name = "compound_46_soy"

[[feed]]
cft_id = 30
display_name = "Soybean cake/meal"
certified = false
region_name = "Global (world)"
cft_name = "soybean_meal"

[[feed]]
cft_id = 36
display_name = "Soybean"
certified = false
region_name = "Poland"
cft_name = "soybean"

[[feed]]
cft_id = 42
display_name = "Fodder beet"
certified = false
region_name = "Poland"
cft_name = "fodder_beet"

[[feed]]
cft_id = 48
display_name = "Sugar beet pulp"
certified = false
region_name = "Poland"
cft_name = "sugar_beet_pulp"

[[feed]]
cft_id = 78
display_name = "Molasses"
certified = false
region_name = "Poland"
cft_name = "molasses"

[[feed]]
cft_id = 23
display_name = "Dried distillers grains (DDGS) / Draff"
certified = false
region_name = "European Union + EFTA"
cft_name = "dried_distillers_grains"

[[feed]]
cft_id = 24
display_name = "Brewerâ€™s grain"
certified = false
region_name = "European Union + EFTA"
cft_name = "brewers_grain"

[[feed]]
cft_id = 35
display_name = "Other oil cake/meal"
certified = false
region_name = "Global (world)"
cft_name = "other_oil_meal"

[[feed]]
cft_id = 80
display_name = "Mineral mix"
certified = false
region_name = "European Union + EFTA"
cft_name = "mineral_mix"

[[feed]]
cft_id = 75
display_name = "Bypass fat"
certified = false
region_name = "European Union + EFTA"
cft_name = "bypass_fat"
