[server]
runOnSave = true
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#0d9488"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#334155"
secondaryBackgroundColor = "#475569"
textColor = "#e2e8f0"