[server]
runOnSave = true
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#0d9488"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"
chartCategoricalColors = [
  "#2a9df4", # primary blue
  "#14b8a6", # teal accent
  "#0ea5e9", # light blue
  "#22c55e", # green
  "#6366f1", # indigo
  "#0f766e", # dark teal
  "#4b5563", # gray
]

[theme.sidebar]
backgroundColor = "#334155"
secondaryBackgroundColor = "#475569"
textColor = "#e2e8f0"