[supabase-public]
url = "https://aprgqfxrciaewejiaans.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcmdxZnhyY2lhZXdlamlhYW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNzYzMTUsImV4cCI6MjA4MDg1MjMxNX0.WaDGwSOynYK5XxTc4NXylw7QL1WmHhMHvWZuxqU1xXA"