[supabase-public]
url = "https://aprgqfxrciaewejiaans.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcmdxZnhyY2lhZXdlamlhYW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNzYzMTUsImV4cCI6MjA4MDg1MjMxNX0.WaDGwSOynYK5XxTc4NXylw7QL1WmHhMHvWZuxqU1xXA"

[cft_api]
app_key = 'K3How8hO3SLeL7xEtzkjf6U8n96VM2cWqXGAtArb0YA'
api_key = '6CLSlqV3jGd7rVvra0jOjgcfdbmuTEzDqOxBWieiGGA'
api_url = "https://app.coolfarmtool.org:/api/v1/dairy_product/calculate/"